/* Speedy List AI - static data: marketplaces (researched Oct 2026, see MARKETPLACES.md) + demo AI catalog */
'use strict';
window.SL = window.SL || {};

/* method: 'direct'  = an official seller/posting API exists (OAuth connect, app posts for you)
           'assisted' = no open posting API for third-party apps: app prepares the listing, opens the site, you tap Publish
           'planned'  = exists, but we have not verified it accepts listings from independent sellers */
SL.MARKETS = [
  { id:'ebay', name:'eBay', mono:'eB', hue:'#e53238', method:'direct', region:'US + global',
    good:'National reach. Ships countertop units & smallwares; local-pickup option for heavy gear.',
    how:'Official Sell Inventory API (seller signs in with eBay OAuth).',
    site:'https://www.ebay.com/sl/sell', src:'https://developer.ebay.com/api-docs/sell/inventory/overview.html' },
  { id:'nextdoor', name:'Nextdoor', mono:'Nd', hue:'#1fa45a', method:'direct', region:'US neighborhoods',
    good:'Neighbors & nearby restaurant owners. Fast local pickup, no shipping.',
    how:'Publish API supports For Sale & Free posts; API access is by application.',
    site:'https://nextdoor.com/for_sale_and_free/', src:'https://developer.nextdoor.com/reference/create-fsf-post-3' },
  { id:'facebook', name:'Facebook Marketplace', mono:'FB', hue:'#1877f2', method:'assisted', region:'US + global',
    good:'Biggest local buyer pool for reach-ins, ranges, prep tables & stainless.',
    how:'Listing API is limited to approved Marketplace partners - we pre-fill, you tap Publish.',
    site:'https://www.facebook.com/marketplace/create/item', src:'https://developers.facebook.com/docs/marketplace/partnerships/' },
  { id:'craigslist', name:'Craigslist', mono:'CL', hue:'#7b4fd6', method:'assisted', region:'US + Canada',
    good:'Local cash buyers. "Business/commercial" category is made for this.',
    how:'Bulk posting interface is only for approved Craigslist accounts.',
    site:'https://post.craigslist.org/', src:'https://www.craigslist.org/about/bulk_posting_interface' },
  { id:'offerup', name:'OfferUp', mono:'OU', hue:'#00ab80', method:'assisted', region:'US',
    good:'Local buyers for big, heavy items picked up in person.',
    how:'No public posting API; OfferUp Business Portal is web-only.',
    site:'https://offerup.com/', src:'https://help.business.offerup.com/hc/en-us/articles/27947563430292-Create-listings-with-Business-Portal' },
  { id:'mercari', name:'Mercari', mono:'Me', hue:'#5356ee', method:'assisted', region:'US',
    good:'Shippable smallwares, slicers & countertop gear (prepaid labels up to 50 lb).',
    how:'No public listing API for third-party apps.',
    site:'https://www.mercari.com/sell/', src:'https://www.mercari.com/us/help_center/topics/listing/guides/creating-a-listing/' },
  { id:'86deadstock', name:'86 Deadstock', mono:'86', hue:'#ff6a2b', method:'assisted', region:'US',
    good:'Restaurants helping restaurants: hospitality buyers for kitchen equipment, smallwares & furniture.',
    how:'No public listing API found - we pre-fill, you tap Publish.',
    site:'https://www.86deadstock.com/', src:'https://www.86deadstock.com/' },
  { id:'ket', name:'Kitchen Equipment Trader', mono:'KT', hue:'#d9822b', method:'assisted', region:'US',
    good:'Commercial-kitchen buyers & dealers. Free for individual sellers.',
    how:'No public listing API found.',
    site:'https://kitchenequipmenttrader.com/sell/restaurant', src:'https://kitchenequipmenttrader.com/sell/restaurant' },
  { id:'rbo', name:'RestaurantBuyOuts', mono:'RB', hue:'#c0392b', method:'assisted', region:'US',
    good:'Dedicated used-restaurant-equipment marketplace, searchable by category & location.',
    how:'No public listing API found.',
    site:'https://restaurantbuyouts.com/', src:'https://restaurantbuyouts.com/' },
  { id:'fss', name:'Food Service Surplus', mono:'FS', hue:'#2d8f85', method:'assisted', region:'US',
    good:'B2B: operators & dealers sourcing used commercial kitchen equipment.',
    how:'No public listing API found.',
    site:'https://www.foodservicesurplus.com/sell-used-restaurant-equipment', src:'https://www.foodservicesurplus.com/sell-used-restaurant-equipment' },
  { id:'rec', name:'Restaurant Equipment Classifieds', mono:'RC', hue:'#8e6b3a', method:'assisted', region:'US',
    good:'Free photo ads (up to 90 days) for food-service equipment.',
    how:'No public listing API found.',
    site:'https://www.restaurant-equipment-classifieds.com/', src:'https://www.restaurant-equipment-classifieds.com/' },
  { id:'boe', name:'Bid on Equipment', mono:'BoE', hue:'#3a6ea5', method:'assisted', region:'US + global',
    good:'Industrial & food-processing buyers. Free to list, 10% seller commission on sale.',
    how:'Listings are reviewed by BoE staff before going live; no public API found.',
    site:'https://www.bid-on-equipment.com/howtosell', src:'https://www.bid-on-equipment.com/howtosell' },
  { id:'machinio', name:'Machinio', mono:'Mc', hue:'#2a7de1', method:'assisted', region:'Global',
    good:'Dealers with bigger inventories. Kitchen & Restaurant Equipment category (paid advertiser plan).',
    how:'Approved advertisers list via Machinio System or inventory feeds; no open posting API.',
    site:'https://www.machinio.com/sell', src:'https://www.machinio.com/sell' },
  { id:'equipnet', name:'EquipNet', mono:'EN', hue:'#0f6db3', method:'assisted', region:'Global',
    good:'Food & beverage processing and plant equipment. Free to list.',
    how:'Self-post or managed sale; no public API found.',
    site:'https://www.equipnet.com/sell-equipment/', src:'https://www.equipnet.com/sell-equipment/' },
  { id:'equipt', name:'Equipt', mono:'Eq', hue:'#e0a020', method:'assisted', region:'US',
    good:'Dealer-bid: describe the item, dealers send competing offers. No commission.',
    how:'No public listing API found.',
    site:'https://www.equipt.com/sell/categories/restaurant-equipment', src:'https://www.equipt.com/sell/categories/restaurant-equipment' },
  { id:'ironplanet', name:'IronPlanet', mono:'IP', hue:'#f2a900', method:'assisted', region:'US + global',
    good:'Whole-kitchen lots via weekly online auctions & Marketplace-E (consignment).',
    how:'Consign through an IronPlanet rep; no open posting API.',
    site:'https://www.ironplanet.com/main/want-to-sell.jsp', src:'https://www.ironplanet.com/sellers-faq' },
  { id:'kijiji', name:'Kijiji (Canada)', mono:'Kj', hue:'#373373', method:'assisted', region:'Canada',
    good:'Canada\'s big local classifieds - restaurant & commercial equipment sells locally.',
    how:'No official posting API for third parties.',
    site:'https://www.kijiji.ca/p-admarkt-post-ad.html', src:'https://www.kijiji.ca/' },
  { id:'allsurplus', name:'AllSurplus', mono:'AS', hue:'#5a6270', method:'planned', region:'US + global',
    good:'Liquidity Services surplus marketplace - big liquidations.',
    how:'Planned: not yet verified for independent sellers.',
    site:'https://www.allsurplus.com/', src:'https://www.allsurplus.com/' },
  { id:'hibid', name:'HiBid / Proxibid auctions', mono:'Hb', hue:'#5a6270', method:'planned', region:'US',
    good:'Online auction platforms run by local auctioneers - closeouts & full kitchens.',
    how:'Planned: sellers usually go through a partner auctioneer; not verified.',
    site:'https://hibid.com/', src:'https://hibid.com/' }
];

SL.GOLD = { 'True':150, 'Hobart':200, 'Vulcan':150, 'Imperial Brown':125 };

SL.CONDITIONS = [
  { id:'like', label:'Like New', c:0.70, hint:'Clean, tested, minimal wear' },
  { id:'good', label:'Good', c:0.50, hint:'Works great, normal wear' },
  { id:'work', label:'Workhorse', c:0.30, hint:'Runs, cosmetic wear / needs TLC' }
];

/* Demo AI catalog: the prototype does NOT analyze photos - it picks one of these (filename keywords, else True T-49). */
SL.DEMO_ITEMS = [
  { key:/true|t-?49|reach|fridge|refrig|cooler|freezer/i, brand:'True', model:'T-49', cat:'Refrigeration',
    name:'True T-49 Two-Section Reach-In Refrigerator', retail:6350, conf:92,
    specs:['2 solid swing doors','~49 cu. ft.','115V plug-in','Stainless front, aluminum sides','Bottom-mount compressor'] },
  { key:/hobart|mixer|hl200|dough/i, brand:'Hobart', model:'HL200 Legacy 20-qt', cat:'Food Prep',
    name:'Hobart HL200 Legacy 20-Quart Planetary Mixer', retail:6100, conf:89,
    specs:['20-qt bowl, beater & hook','3 fixed speeds + stir','115V','#12 attachment hub','Bowl guard'] },
  { key:/vulcan|range|burner|stove|oven/i, brand:'Vulcan', model:'36S-6B', cat:'Cooking',
    name:'Vulcan 36S-6B 36" 6-Burner Gas Range with Oven', retail:3400, conf:88,
    specs:['Six 30,000 BTU open burners','Standard oven','Natural gas','Stainless front & sides','6" adjustable legs'] },
  { key:/imperial|brown|walk/i, brand:'Imperial Brown', model:'8\' x 10\' Walk-In', cat:'Refrigeration',
    name:'Imperial Brown 8\' x 10\' Walk-In Cooler Box', retail:11500, conf:84,
    specs:['Insulated panels, 4" walls','Door with strip curtain & light','Floor included','Remote or top-mount system','Disassembled for transport'] },
  { key:/pitco|fryer|fry/i, brand:'Pitco', model:'40D', cat:'Cooking',
    name:'Pitco 40D 40-lb Gas Fryer', retail:2100, conf:86,
    specs:['40-50 lb oil capacity','Natural gas, ~105,000 BTU','Millivolt thermostat','Two baskets','Stainless tank'] },
  { key:/manitowoc|ice/i, brand:'Manitowoc', model:'IYT0500A + bin', cat:'Ice Machines',
    name:'Manitowoc IYT0500A Indigo NXT Ice Machine with Bin', retail:5200, conf:85,
    specs:['~500 lb/day half-dice ice','Air-cooled, 115V','Bin included','Cleaning cycle reminders','Stainless exterior'] }
];
